"use strict";

module.exports = [
  require("./rules/am001"),
  require("./rules/am002"),
  require("./rules/am003"),
  require("./rules/am004"),
  require("./rules/am005"),
  require("./rules/am006"),
  require("./rules/am007"),
  require("./rules/am008"),
  require("./rules/am009"),
  require("./rules/am010"),
  require("./rules/am011"),
  require("./rules/am012"),
  require("./rules/am013"),
  require("./rules/am014"),
  require("./rules/am015"),
  require("./rules/am016"),
  require("./rules/am017"),
  require("./rules/am018"),
  require("./rules/am019"),
  require("./rules/am020"),
  require("./rules/am021"),
  require("./rules/am022"),
  require("./rules/am023"),
  require("./rules/am024"),
  require("./rules/am026"),
  require("./rules/am028"),
  require("./rules/am029"),
];
