"use strict";

module.exports = [
  require("./rules/AM001"),
  require("./rules/AM002"),
  require("./rules/AM003"),
  require("./rules/AM004"),
  require("./rules/AM005"),
  require("./rules/AM006"),
  require("./rules/AM007"),
  require("./rules/AM008"),
  require("./rules/AM009"),
  require("./rules/AM010"),
  require("./rules/AM011"),
  require("./rules/AM012"),
  require("./rules/AM013"),
  require("./rules/AM014"),
  require("./rules/AM015"),
  require("./rules/AM016"),
  require("./rules/AM017"),
  require("./rules/AM018"),
  require("./rules/AM019"),
  require("./rules/AM020"),
  require("./rules/AM021"),
  require("./rules/AM022"),
  require("./rules/AM023"),
  require("./rules/AM024"),
  require("./rules/AM026"),
  require("./rules/AM028"),
  require("./rules/AM029"),
];
