name: Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install Dependencies
      run: npm install

    - name: Build Plugin
      run: npm run build-plugin

    - name: Package VS Code Extension
      run: vsce package

    - name: Move files to releases directory
      run: |
        mkdir -p releases/plugin
        mkdir -p releases/extension
        mv your-plugin.standalone.js releases/plugin/
        mv your-extension.vsix releases/extension/

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Plugin File
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releases/plugin/markdown-it-adobe-plugin.js
        asset_name: markdown-it-adobe-plugin.js
        asset_content_type: application/javascript

    - name: Upload VSIX File
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./releases/extension/adobe-markdown-authoring.vsix
        asset_name: adobe-markdown-authoring.vsix
        asset_content_type: application/octet-stream
